### ISSUE TITLE
Adding the binding to "fish_user_key_bindings.fish" doesn't seem to work bw sessions

### ISSUE THREAD

**Issue by sourabhtk37** [jbonjean/re-search#12]
The [fish bind](https://fishshell.com/docs/current/commands.html#bind) needs to have a function to describe the bindings. 
 ```
Key bindings are not saved between sessions by default. Bare bind statements in config.fish won't have any effect because it is sourced before the default keybindings are setup. To save custom keybindings, put the bind statements into a function called fish_user_key_bindings, which will autoloaded
```

Therfore, it needs to have, else the file `~/.config/fish/functions/fish_user_key_bindings.fish` have to sourced each time
```
function fish_user_key_bindings
    bind \cr re_search
end
```

**Comment by jbonjean** [comment]
`~/.config/fish/functions/fish_user_key_bindings.fish` is supposed to be loaded automatically by fish, this was the recommended solution to inject custom binding (fish-shell/fish-shell#1495).
Did this behavior change?

**Comment by sourabhtk37** [comment]
It doesn't seems to auto load and you have to source it each time between sessions, unless you put the bindings in a function `fish_user_key_bindings` which will be auto-loaded.

**Comment by jbonjean** [comment]
I just tested following the steps from the README on a vanilla fish 2.6.0 installation and it worked fine. Maybe something is wrong in your setup.

**Comment by sourabhtk37** [comment]
Yeah, It seems so. Anyways thanks. :heart:

**Comment by sourabhtk37** [comment]
Closing this

**Comment by SferaDev** [comment]
This same thing happened to me after installing nvm on fish!

Steps to reproduce:

- Install ``fish``
- Install ``re-search``
- Binding works as the readme
- Install ``nvm`` and ``nvm-fish``
- Binding does not work anymore

The solution of adding it in a function appears to work fine though!
