### ISSUE TITLE
Make prompt configurable

### ISSUE THREAD

**Issue by hupfdule** [jbonjean/re-search#15]
Just an idea after having written the PR about the changed prompt colors.

If you don't like the idea, feel free to close this issue.

I would be nice if the appearance of the prompt could be configured by the user without recompliation, either via environment variable or as commandline parameter.

My idea is to provide a formatting string that contains
 - placeholders for the strings generated by re-search (direction, search string, search result, result id)
 - color codes for coloring the prompt
 - additional characters to add before/after/around the placeholders

See the following example as a possible formatting string that resembles the current prompt:

`export RE_SEARCH_PROMPT='\033[32m<${direction}> \033[36m${search_term} (${history_index})[\033[0m${result}\033[36m]'`

The placeholders are all surrounded by `${}`. Characters outside such placeholders are used as is (including the ANSI color codes). The placeholders themseleves are replaced by the actual values calculated by re-search.

Here is a colorized variant to make it easier to distinguish the parts of the formatting string.
![prompt](https://user-images.githubusercontent.com/36069345/55799120-ea2c9b00-5ad0-11e9-9c43-b8cc9bb97e90.png)

blue: color codes
red: placeholders
black: additional characters

One thing I am not sure about is whether to provide the ability to set the formatting string via environment variable or as parameter on calling re-search or both.
It would be nice to provide both, but I don't know which one should override the other. Maybe that's a reason to provide only one of them.

Advantage of environment variable: It can easily changed on the fly by just changing that environment variable (like e.g. PS1 for bash). But the definition of the prompt and the mapping to re-search are separated.
Advantage of commandline parameter: It can be defined where the mapping to re-search is defined. But it is harder to change it on the fly.

When thinking more about it, I have a slight preference to the environment variable.

Anyways, it should be optional and the current one (or the above mentioned example) should be provided as default if not redefined by the user.

What do you think about that?

**Comment by jbonjean** [comment]
When I implemented `re-search`, I assumed that users basically never change this type of settings. I provided a mechanism to customize it via local `config.h`, and even if it is not the most user friendly, I felt it was enough and simpler than supporting runtime customization.

I'm not against this idea, and I actually like the environment variable approach, because of its similarity with PS1 like you mentioned. That being said, I don't really need it and don't have much time to work on this, but I would gladly accept a pull request, assuming it doesn't bring too much complexity.

**Comment by hupfdule** [comment]
Fair enough. I also came to the idea only since it is already configurable in some way.

Unfortunately my knowledge of C isn't good enough. 

If you want you can tag this issue as "help wanted" in the hope someone other is interested to implement it. Or just close it if you don't think that will happen.

**Comment by jbonjean** [comment]
Sorry but yes, I don't think that will happen. I'm going to close the issue for now.
