### ISSUE TITLE
Pressing an unsupported key combination should do nothing

### ISSUE THREAD

**Issue by hupfdule** [jbonjean/re-search#18]
Currently when pressing an unsupported key combination like `Ctrl-a` re-search goes one step further in the history (in the current search direction). 
This is quite an unexpected behaviour. It should do nothing instead.

For example:
This is the current situation (while in a history search)
![before](https://user-images.githubusercontent.com/36069345/57695474-ac321200-764e-11e9-9104-438fedba9daf.png)

It is currently at the first history entry.
After pressing `Ctrl-a` it is
![after](https://user-images.githubusercontent.com/36069345/57695542-cec42b00-764e-11e9-8823-c15e528c2679.png)

It jumped to the second history entry.
However, it should have remained at the first history entry.

**Comment by jbonjean** [comment]
I agree, this is an unexpected behaviour. I will look into it when I have time.
