### ISSUE TITLE
compilation on mac

### ISSUE THREAD

**Issue by tunder** [jbonjean/re-search#2]
clang: error: cannot specify -o when generating multiple output files

in order to compile on osx i had to remove "config.h" dependency file from Makefile line 7.
probably is working without it on linux too.

**Comment by endrebak** [comment]
Worked wonderfully on my mac. 

```
OS X Yosemite
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```
